sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: hpcKR9dp1guZpbkrQQn6JVPmcAr6WyzcB80EuMGEms6WQvk+e2dS5jui0hK5JWvrXxa41y0UUUCytHGFsfLgNAXNRLnISsQ3aKqYHSmVSPAXX+GOt11oKwzZkEwXkHF7vJGgbu1jC/6KbkvRtiRJPcvWcB2Cuh20tbqB/+ODYe+pzRpjQ9Zk567EaiJVleRbCszI+xTQjOZrZfeiPFYL5yqXS0DEwZFfHBBzeHMhpuUmD/taEG0BKbyqEM3rWptEYZGHp9MdwW4iauSkJPlWBJzC17mh9JS4b+2uRF05qTwdItN4PUpiNFxuOTORgcev+yPJn24HFh3BePLgd+CthiJpFDxc6UJ13Y2RcNeoT0tEX/LR3ArxRsnV35r6Bh+/P1ixt0FtHfR4YqvBUCKf6sq2nqaN7xFwHez4N6xCbH90h9hm1ZMPLG2wFVs8jTPcnqnZ5BKXonUNzz4FwEiYOCIZ/HkpYZo6U2jTB1L7ugg8N1+j7sBw4Qc/qjFJ9I4+ocOQGZClYiEZfKpdurku6qT75flsWGMkDWJYZrnnB7+AEc7LNfsCvAMesgwd5GaRVGpD9xxEU3nAXy2UiZVaTzZHqFWGYJRHI8NZLH4Q4vAGC5rcHKQoFbgIG4SKgcMIcoiTZiEy1pjguVF1fFmJ0liHOfTwqqglSDb6XHeEIc0=
  branches: 
  only:
  - master
